<a href="https://colab.research.google.com/github/Janardhan83/NumPy-for-Data-Science/blob/main/Student_Marks_Analysis/01_Student_Marks_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Mini Project 1**
#Student Marks Analysis using NumPy

##Problem Statement

A school wants to analyze student performance using NumPy.

You are given marks of students in 3 subjects:

Math

Science

English

**Your task is to analyze the marks data and extract useful insights such as:**

-total marks

-average marks

-highest and lowest

-pass/fail analysis

-topper identification

This project helps understand how NumPy is used in real-world data analysis.

##NumPy Dataset Format
marks = [
  
    [85, 78, 92],

    [70, 88, 80],

    [60, 45, 70],

    [95, 90, 93],

    [40, 50, 65]
]

##Dataset

| Student   | Math | Science | English |
| --------- | ---- | ------- | ------- |
| Student 1 | 85   | 78      | 92      |
| Student 2 | 70   | 88      | 80      |
| Student 3 | 60   | 45      | 70      |
| Student 4 | 95   | 90      | 93      |
| Student 5 | 40   | 50      | 65      |


#1.Basic Analysis



Q1.

Convert the dataset into a NumPy array.

In [ ]:
import numpy as np
marks =np.array( [
    [85, 78, 92],
    [70, 88, 80],
    [60, 45, 70],
    [95, 90, 93],
    [40, 50, 65]
])

In [ ]:
students = np.array([
    "Student 1",
    "Student 2",
    "Student 3",
    "Student 4",
    "Student 5"
])

In [ ]:
subjects = np.array([
    "Math",
    "Science",
    "English"
])


Q2.

Display the entire dataset.

In [ ]:
print(marks)
print('\n',students)
print('\n',subjects)

[[85 78 92]
 [70 88 80]
 [60 45 70]
 [95 90 93]
 [40 50 65]]

 ['Student 1' 'Student 2' 'Student 3' 'Student 4' 'Student 5']

 ['Math' 'Science' 'English']


Q3.

Find:

shape

dimensions

size

datatype

of the array.

In [ ]:
print(f'shape of numpy :{marks.shape}\n')
print(f'dimensions of numpy:{marks.ndim}\n')
print(f'size of numpy :{marks.size}\n')
print(f'datatype of the array:{marks.dtype}\n')

shape of numpy :(5, 3)

dimensions of numpy:2

size of numpy :15

datatype of the array:int64



##2.Student-wise Analysis

Q4.

Calculate total marks of each student.

In [ ]:
print(marks)
total=marks.sum(axis=1)#axis =1 here row wise sum operation
for i in range(total.size):
  print(f'student{i+1} total_marks :{total[i]:.2f}')


[[85 78 92]
 [70 88 80]
 [60 45 70]
 [95 90 93]
 [40 50 65]]
student1 total_marks :255.00
student2 total_marks :238.00
student3 total_marks :175.00
student4 total_marks :278.00
student5 total_marks :155.00


Q5.

Calculate average marks of each student.

In [ ]:
avg_marks=marks.mean(axis=1)
for i in range(avg_marks.size):
  print(f'student{i+1} avg_marks :{avg_marks[i]:.2f}')


student1 avg_marks :85.00
student2 avg_marks :79.33
student3 avg_marks :58.33
student4 avg_marks :92.67
student5 avg_marks :51.67


Q6.

Find the topper of the class based on total marks.

In [ ]:
total=marks.sum(axis=1)
print(f'{students[total.argmax()]} is  the topper of class: {total.max()}')

Student 4 is  the topper of class: 278


Q7.

Find the student with the lowest total marks.

In [ ]:
print(f'{students[total.argmin()]} is  the lowest of class: {total.min()}')

Student 5 is  the lowest of class: 155


##Subject-wise Analysis

Q8.

Find highest marks in each subject.

In [ ]:
highest_marks=marks.max(axis=0)
for sub , mark in zip(subjects,highest_marks):
  print(f'{sub} : {mark}')


Math : 95
Science : 90
English : 93


Q9.

Find lowest marks in each subject.

In [ ]:
lowest_marks=marks.min(axis=0)
for sub , mark in zip(subjects,lowest_marks):
  print(f'{sub} : {mark}')


Math : 40
Science : 45
English : 65


Q10.

Find average marks of each subject.

In [ ]:
avg_marks=marks.mean(axis=0)
for sub , mark in zip(subjects,avg_marks):
  print(f'{sub} : {mark}')

Math : 70.0
Science : 70.2
English : 80.0


##Pass/Fail Analysis

Q11.

Assume:

Pass marks = 50

Find students who passed in all subjects.

In [ ]:
print(marks)

[[85 78 92]
 [70 88 80]
 [60 45 70]
 [95 90 93]
 [40 50 65]]


In [ ]:
for stu,i in zip(students,marks>50):
  if all(i) == True:
    print(stu ,'pass')

Student 1 pass
Student 2 pass
Student 4 pass


Q12.

Find students who failed in at least one subject.

In [ ]:
for stu,i in zip(students,marks<50):
  if any(i) == True:
    print(stu ,'fail')

Student 3 fail
Student 5 fail


Q13. Passed Students Data

In [ ]:
print('student',subjects)
for stu , mar in zip(students,marks):
  if all(mar>50)==True:
    print(stu,':',mar)

student ['Math' 'Science' 'English']
Student 1 : [85 78 92]
Student 2 : [70 88 80]
Student 4 : [95 90 93]


## Advanced Analysis

Q14.

Find percentage of each student.

In [ ]:
sum_mark=marks.sum(axis=1)
print('percentage of each student:')
for stu , sum in zip(students,sum_mark):
  print(f'{stu} :{(sum/300)*100:.2f} %')

percentage of each student:
Student 1 :85.00 %
Student 2 :79.33 %
Student 3 :58.33 %
Student 4 :92.67 %
Student 5 :51.67 %


Q15.

Assign grades using average marks:
| Average Marks | Grade |
| ------------- | ----- |
| 90+           | A     |
| 75-89         | B     |
| 60-74         | C     |
| Below 60      | Fail  |


In [ ]:
print("\nGrades:")
avg_mark=marks.mean(axis=1)
for stu , avg in zip(students,avg_mark):
  if avg >= 90:
    print(f'{stu} grade A')
  elif avg >=75:
    print(f'{stu} grade B')
  elif avg>=60:
    print(f'{stu} grade C')
  else:
    print(stu,'grade Fail')



Grades:
Student 1 grade B
Student 2 grade B
Student 3 grade Fail
Student 4 grade A
Student 5 grade Fail


Q16.

Find subject topper for:

Math

Science

English

In [ ]:
print(marks)

[[85 78 92]
 [70 88 80]
 [60 45 70]
 [95 90 93]
 [40 50 65]]


In [ ]:
print("\nSubject Toppers:")
for i in range(len(subjects)):
  index=np.argmax(marks[:,i])
  print(f'{subjects[i]} :-  {students[index]} = {np.max(marks[:,i])}')


Subject Toppers:
Math :-  Student 4 = 95
Science :-  Student 4 = 90
English :-  Student 4 = 93


Q17.

Find overall class average.

In [ ]:
print(f'Overall class average : {marks.mean()}')

Overall class average : 73.4


In [ ]:
## using loops
sum=0
count=0
for row in marks:
  for value in row:
    count+=1
    sum+=value
print(f'overall average is {sum/count}')


overall average is 73.4


Q18.

Count how many students passed and failed.

In [ ]:
# using loops
Passed_Students = 0
Failed_Students = 0
for student in marks:
  if all(student >=50 )==True:
    Passed_Students+=1
  else:
    Failed_Students+=1
print(f'passed students:{Passed_Students} and failed_students:{Failed_Students}')

passed students:3 and failed_students:2


**Q19. Students Sorted by Total Marks**


np.argsort() is a NumPy function that gives the indexes (positions) that would sort an array.

example 1:

arr = np.array([40, 10, 20])

print(np.sort(arr))
#### [10 20 40]

print(np.argsort(arr))
#### [1 2 0]

In [ ]:
total_mark=marks.sum(axis=1)
sort_index=total_mark.argsort()[::-1]
rank =1
for ind in sort_index:
  print(f'{rank}. {students[ind]} = {total_mark[ind]}')
  rank+=1


1. Student 4 = 278
2. Student 1 = 255
3. Student 2 = 238
4. Student 3 = 175
5. Student 5 = 155


Q20.

Find students scoring above class average.

In [ ]:
class_avg =marks.mean()
for stu in range(len(students)):
  if marks[stu].mean() >= class_avg:
    print(f'{students[stu]}')


Student 1
Student 2
Student 4
