<a href="https://colab.research.google.com/github/Janardhan83/NumPy-for-Data-Science/blob/main/01_numpy_note.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Basics

NumPy (Numerical Python) is a powerful Python library used for:
- Numerical computations
- Working with arrays
- Mathematical operations
- Data Science and Machine Learning tasks

NumPy is faster and more efficient than Python lists.

## Importing NumPy

In [1]:
import numpy as np ## np is an alias (short name) for NumPy

## Creating Arrays
An array is a collection of elements stored in a structured format.

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Creating 2D Array

In [3]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)

[[1 2 3]
 [4 5 6]]


3.3 zeros()


Creates an array filled with zeros.

Syntax:

###np.zeros(shape)

In [4]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


3.4 ones()

In [5]:

print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.5 arange()

Definition

Creates array with a range of values.

Syntax

np.arange(start, stop, step)

In [6]:
print(np.arange(1, 10, 2))

[1 3 5 7 9]


3.6 linspace()

Definition

Creates evenly spaced values between two numbers.


Syntax

np.linspace(start, stop, number_of_values)

In [7]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


3.7 eye()

Definition

Creates an identity matrix.



In [8]:
print(np.eye(3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Array Attributes
Attributes give information about the array.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)

(2, 3)


ndim

print(arr.ndim)

Definition

Returns number of dimensions.

In [10]:

print(arr.ndim)

2


size

Definition

Returns total number of elements.

In [11]:
print(arr.size)

6


dtype

print(arr.dtype)

Definition

Returns data type of array elements.

In [12]:
print(arr.dtype)

int64


## Array Indexing
Indexing is used to access specific elements.

1D Indexing

In [13]:
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[-1])

10
40


2D Indexing

In [14]:

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2[0, 1])
print(arr2[1, 2])

2
6


##6. Array Slicing
*italicized text*
Definition

Slicing is used to access multiple elements.

In [15]:
# 1D Slicing
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr[1:4])

[2 3 4]


In [16]:
# 2D Slicing
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2[:, 1:])

[[2 3]
 [5 6]]


##7. Array Operations

In [17]:
# Addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [18]:
#Subtraction
print(a - b)

[-3 -3 -3]


In [19]:
# Multiplication
print(a * b)

[ 4 10 18]


In [20]:
# Division
print(a / b)

[0.25 0.4  0.5 ]


###Scalar Operations


In [21]:
print(a + 10)
print(a * 2) #a=[1 2 3]

[11 12 13]
[2 4 6]


##8. Broadcasting
Definition

Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [22]:
arr = np.array([1, 2, 3])

print(arr + 5)

[6 7 8]


##9. Reshape & Flatten

###reshape()

Definition

Changes shape of array without changing data.

Syntax

##array.reshape(rows, columns)

In [23]:
arr = np.arange(1, 13)

print(arr)

reshaped = arr.reshape(3, 4)

print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


flatten()

Definition

Converts multi-dimensional array into 1D array.

In [24]:

print(reshaped.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


##10. Aggregate Functions

In [25]:
# sum()
arr = np.array([1, 2, 3, 4])

print(arr.sum())

10


In [26]:
# mean()
print(arr.mean())

2.5


In [27]:
# max()
print(arr.max())

4


In [28]:
# min()
print(arr.min())

1


##11. Statistical Functions

In [29]:
# std()
print(arr)
print(arr.std())

[1 2 3 4]
1.118033988749895


In [30]:
# var()
print(arr.var())

1.25


In [31]:
# median()
print(np.median(arr))

2.5


##12. Copy vs View

A view shares the original data, while a copy gets its own brand-new data.



In [32]:
# Copy
arr = np.array([1, 2, 3])

copy_arr = arr.copy()

copy_arr[0] = 100

print(arr)
print(copy_arr)

[1 2 3]
[100   2   3]


In [33]:
# View
view_arr = arr.view()

view_arr[0] = 500

print(arr)
print(view_arr)

[500   2   3]
[500   2   3]


## 13. Boolean Masking & Filtering

Boolean Masking is a fast way to filter out data in an array by using a list of True and False values

In [34]:
arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)

[False False  True  True  True]


In [35]:
# Filtering
print(arr[arr > 25])

[30 40 50]


In [36]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Create the mask: Is the remainder 0?
even_mask = (numbers % 2 == 0)

# Filter the array
even_numbers = numbers[even_mask]

print(even_numbers)
# Output: [2, 4, 6, 8]

[2 4 6 8]


In [37]:
scores = np.array([55, 72, 88, 95, 64, 81, 90])

# Mask: Score must be > 70 AND < 90
b_mask = (scores > 70) & (scores < 90)

b_students = scores[b_mask]

print(b_students)
# Output: [72, 88, 81]

[72 88 81]


##14. Random Module

In [38]:
# random integers
print(np.random.randint(1, 10, 5)) #randint(start,stop,no_of_elements)

[1 5 6 3 2]


In [39]:
np.random.seed(42)#always same out put
print(np.random.randint(1, 100, 5))

[52 93 15 72 61]


In [40]:
# random floats
print(np.random.rand(3,3))#rand(shape)

[[0.59685016 0.44583275 0.09997492]
 [0.45924889 0.33370861 0.14286682]
 [0.65088847 0.05641158 0.72199877]]


In [41]:
print(np.random.randn(20,2)) # normal distribustion randn(shape)

[[ 0.02222183 -0.42779291]
 [-0.53181741 -0.1174755 ]
 [ 0.2220789  -0.7679765 ]
 [ 0.1424646  -0.03465218]
 [ 1.13433927 -0.10474555]
 [-0.52512285  1.91277127]
 [-2.02671962  1.11942361]
 [ 0.77919263 -1.10109776]
 [ 1.13022819  0.37311891]
 [-0.38647295 -1.15877024]
 [ 0.56611283 -0.70445345]
 [-1.3779393  -0.35311665]
 [-0.46146572  0.06665728]
 [-0.17628566  1.20089277]
 [ 0.69839894 -0.17162884]
 [-0.90718658  1.18862573]
 [ 0.78553212  2.65601009]
 [ 0.26348604  1.64177112]
 [ 0.4608163   0.08592347]
 [-1.50995728  0.72150246]]


##15. Useful Functions

In [42]:
# unique()
arr = np.array([[1, 2, 2],[3, 4, 4]])

print(np.unique(arr)) # unique values return in 1D array

[1 2 3 4]


In [43]:
# sort()
# arr = np.array([5, 2, 8, 1])
print(np.sort(arr))

[[1 2 2]
 [3 4 4]]


In [44]:
# concatenate()
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.concatenate((a, b)))

a = np.array([1, 2])
b = np.array([3, 4])

print(np.concatenate((a, b)))

[[1 2]
 [3 4]]
[1 2 3 4]


##16. Conclusion
# Conclusion

In this notebook, we learned:
- Creating arrays
- Array indexing and slicing
- Array operations
- Broadcasting
- Reshaping arrays
- Statistical functions
- Boolean masking
- Random module
- Useful NumPy functions

NumPy is the foundation of Data Science, Machine Learning, and Deep Learning.