<a href="https://colab.research.google.com/github/Janardhan83/NumPy-for-Data-Science/blob/main/2_NumPy_Practice_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Practice Questions

Question 1

Create a NumPy array from 1 to 10.

In [1]:
import numpy as np

arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Question 2

Create a 3×3 array filled with zeros.

In [2]:
print(np.zeros((3,3),dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Question 3

Create a 4×4 identity matrix.

In [3]:
print(np.eye(4,dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Question 4

In [4]:
# Find:

# shape
# dimensions
# total elements
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

Shape: (2, 3)
Dimensions: 2
Size: 6


Question 5

Slice elements from index 2 to 6.

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[2:7])

[3 4 5 6 7]


Question 6

Extract second column from 2D array.

In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[:, 1])

[2 5 8]


Question 8

Perform:

addition

subtraction

multiplication

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]


Question 9

Add 100 to every element using broadcasting.

In [8]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


print(arr + 100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


Question 10

Reshape array into 3×4 matrix.

arr = np.arange(1, 13)


In [9]:
arr = np.arange(1, 13)

reshaped = arr.reshape(3, 4)

print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Question 11

Convert 2D array into 1D array.


arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [10]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.flatten())

[1 2 3 4 5 6]


Question 12

Find:

sum

mean

maximum

minimum

arr = np.array([10, 20, 30, 40, 50])


In [11]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())

Sum: 150
Mean: 30.0
Max: 50
Min: 10


Question 13

Find all even numbers using boolean masking.

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [12]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

even=arr % 2 == 0

print(arr[even])

[2 4 6]


Question 14

Generate 5 random integers between 1 and 100.

In [13]:
random_nums = np.random.randint(1, 101, 5)

print(random_nums)

[57  2 46 50 82]


Question 15 (Strong Logic Question)

Replace all negative numbers with 0.

In [14]:
arr = np.array([2, -5, 7, -1, 8, -3])
arr[arr < 0]=0
print(arr)

[2 0 7 0 8 0]
